export const achievementsData = [
  {
    id: "streak_7",
    title: "Week Warrior",
    description: "Maintain a 7-day learning streak",
    icon: "🔥",
    category: "streak",
    xpReward: 50,
    requirement: "Complete lessons on 7 consecutive days",
    rarity: "common",
    isHidden: false,
  },
  {
    id: "streak_30",
    title: "Monthly Master",
    description: "Maintain a 30-day learning streak",
    icon: "⚡",
    category: "streak",
    xpReward: 200,
    requirement: "Complete lessons on 30 consecutive days",
    rarity: "rare",
    isHidden: false,
  },
  {
    id: "streak_100",
    title: "Century Champion",
    description: "Maintain a 100-day learning streak",
    icon: "💎",
    category: "streak",
    xpReward: 500,
    requirement: "Complete lessons on 100 consecutive days",
    rarity: "epic",
    isHidden: false,
  },
  {
    id: "streak_365",
    title: "Year of Growth",
    description: "Maintain a 365-day learning streak",
    icon: "👑",
    category: "streak",
    xpReward: 1500,
    requirement: "Complete lessons on 365 consecutive days",
    rarity: "legendary",
    isHidden: false,
  },
  {
    id: "streak_7_revive",
    title: "Unstoppable",
    description: "Revive a streak after missing just 1 day",
    icon: "♻️",
    category: "streak",
    xpReward: 75,
    requirement: "Restore your streak within 1 day of it breaking",
    rarity: "rare",
    isHidden: true,
  },

  {
    id: "learn_first",
    title: "First Steps",
    description: "Complete your first lesson",
    icon: "🎓",
    category: "learning",
    xpReward: 25,
    requirement: "Complete any lesson for the first time",
    rarity: "common",
    isHidden: false,
  },
  {
    id: "learn_10",
    title: "Dedicated Learner",
    description: "Complete 10 lessons",
    icon: "📚",
    category: "learning",
    xpReward: 100,
    requirement: "Complete 10 different lessons",
    rarity: "common",
    isHidden: false,
  },
  {
    id: "learn_50",
    title: "Knowledge Seeker",
    description: "Complete 50 lessons",
    icon: "🧠",
    category: "learning",
    xpReward: 250,
    requirement: "Complete 50 different lessons",
    rarity: "rare",
    isHidden: false,
  },
  {
    id: "learn_100",
    title: "Scholar",
    description: "Complete 100 lessons",
    icon: "📖",
    category: "learning",
    xpReward: 500,
    requirement: "Complete 100 different lessons",
    rarity: "epic",
    isHidden: false,
  },
  {
    id: "vocab_50",
    title: "Word Collector",
    description: "Learn 50 new vocabulary words",
    icon: "🔤",
    category: "learning",
    xpReward: 100,
    requirement: "Add 50 words to your vocabulary",
    rarity: "common",
    isHidden: false,
  },
  {
    id: "vocab_200",
    title: "Lexicon Builder",
    description: "Learn 200 vocabulary words",
    icon: "📝",
    category: "learning",
    xpReward: 300,
    requirement: "Add 200 words to your vocabulary",
    rarity: "rare",
    isHidden: false,
  },
  {
    id: "vocab_500",
    title: "Word Master",
    description: "Learn 500 vocabulary words",
    icon: "🏆",
    category: "learning",
    xpReward: 600,
    requirement: "Add 500 words to your vocabulary",
    rarity: "epic",
    isHidden: false,
  },
  {
    id: "speak_first",
    title: "Break the Silence",
    description: "Complete your first speaking exercise",
    icon: "🎤",
    category: "learning",
    xpReward: 30,
    requirement: "Record and submit your first speaking answer",
    rarity: "common",
    isHidden: false,
  },
  {
    id: "speak_50",
    title: "Voice of Progress",
    description: "Complete 50 speaking exercises",
    icon: "🗣️",
    category: "learning",
    xpReward: 250,
    requirement: "Complete 50 speaking exercises",
    rarity: "rare",
    isHidden: false,
  },
  {
    id: "grammar_first",
    title: "Rule Follower",
    description: "Master your first grammar rule",
    icon: "⚙️",
    category: "learning",
    xpReward: 40,
    requirement: "Complete a grammar lesson with 90%+ accuracy",
    rarity: "common",
    isHidden: false,
  },
  {
    id: "grammar_25",
    title: "Grammar Guru",
    description: "Master 25 grammar rules",
    icon: "🔧",
    category: "learning",
    xpReward: 200,
    requirement: "Complete 25 grammar lessons with 90%+ accuracy",
    rarity: "rare",
    isHidden: false,
  },

  {
    id: "game_first",
    title: "Play & Learn",
    description: "Play your first game",
    icon: "🎮",
    category: "game",
    xpReward: 25,
    requirement: "Complete any game for the first time",
    rarity: "common",
    isHidden: false,
  },
  {
    id: "game_10",
    title: "Fun Seeker",
    description: "Play 10 games",
    icon: "🎯",
    category: "game",
    xpReward: 100,
    requirement: "Complete 10 different games",
    rarity: "common",
    isHidden: false,
  },
  {
    id: "game_50",
    title: "Game Enthusiast",
    description: "Play 50 games",
    icon: "🎲",
    category: "game",
    xpReward: 300,
    requirement: "Complete 50 different games",
    rarity: "rare",
    isHidden: false,
  },
  {
    id: "game_perfect",
    title: "Flawless Victory",
    description: "Get a perfect score in any game",
    icon: "💯",
    category: "game",
    xpReward: 150,
    requirement: "Achieve 100% score in any game",
    rarity: "rare",
    isHidden: false,
  },
  {
    id: "game_highscore",
    title: "High Scorer",
    description: "Get a score in the top 10%",
    icon: "🥇",
    category: "game",
    xpReward: 200,
    requirement: "Reach a score that ranks in the top 10%",
    rarity: "epic",
    isHidden: true,
  },
  {
    id: "game_all_modes",
    title: "All-Rounder",
    description: "Play all game modes",
    icon: "🎰",
    category: "game",
    xpReward: 250,
    requirement: "Play at least one game in every game mode",
    rarity: "epic",
    isHidden: true,
  },

  {
    id: "special_nightowl",
    title: "Night Owl",
    description: "Study after 10 PM",
    icon: "🦉",
    category: "special",
    xpReward: 50,
    requirement: "Complete a lesson between 10 PM and 5 AM",
    rarity: "rare",
    isHidden: false,
  },
  {
    id: "special_earlybird",
    title: "Early Bird",
    description: "Study before 7 AM",
    icon: "🐦",
    category: "special",
    xpReward: 50,
    requirement: "Complete a lesson between 5 AM and 7 AM",
    rarity: "rare",
    isHidden: false,
  },
  {
    id: "special_weekend_warrior",
    title: "Weekend Warrior",
    description: "Study on both Saturday and Sunday",
    icon: "⚔️",
    category: "special",
    xpReward: 100,
    requirement: "Complete at least one lesson on Saturday and Sunday in the same week",
    rarity: "rare",
    isHidden: false,
  },
  {
    id: "special_weekday_champion",
    title: "Weekday Champion",
    description: "Study every day of the week",
    icon: "📅",
    category: "special",
    xpReward: 150,
    requirement: "Study at least once on all 7 days of the week",
    rarity: "epic",
    isHidden: false,
  },
  {
    id: "special_perfect_day",
    title: "Perfect Day",
    description: "Complete 5+ lessons in a single day",
    icon: "🌟",
    category: "special",
    xpReward: 125,
    requirement: "Complete 5 or more lessons in one calendar day",
    rarity: "rare",
    isHidden: false,
  },
  {
    id: "special_marathon",
    title: "Learning Marathon",
    description: "Study for over 2 hours in one session",
    icon: "🏃",
    category: "special",
    xpReward: 200,
    requirement: "Have a study session longer than 2 hours",
    rarity: "epic",
    isHidden: true,
  },

  {
    id: "hidden_speed_demon",
    title: "Speed Demon",
    description: "Complete a lesson in under 2 minutes",
    icon: "⚡",
    category: "hidden",
    xpReward: 300,
    requirement: "Finish a lesson with a time under 2 minutes",
    rarity: "epic",
    isHidden: true,
  },
  {
    id: "hidden_perfectionist",
    title: "Perfectionist",
    description: "Get 100% accuracy on 10 lessons in a row",
    icon: "🎯",
    category: "hidden",
    xpReward: 500,
    requirement: "Achieve 100% accuracy on 10 consecutive lessons",
    rarity: "legendary",
    isHidden: true,
  },
  {
    id: "hidden_completionist",
    title: "Completionist",
    description: "Complete every available lesson",
    icon: "🏅",
    category: "hidden",
    xpReward: 1000,
    requirement: "Complete all available lessons in the app",
    rarity: "legendary",
    isHidden: true,
  },
  {
    id: "hidden_triple_crown",
    title: "Triple Crown",
    description: "Reach level 10 in vocabulary, grammar, and speaking",
    icon: "👑",
    category: "hidden",
    xpReward: 750,
    requirement: "Reach level 10 in three different skill categories",
    rarity: "legendary",
    isHidden: true,
  },
  {
    id: "hidden_comeback",
    title: "The Comeback",
    description: "Return after a 30+ day absence",
    icon: "🔄",
    category: "hidden",
    xpReward: 200,
    requirement: "Log in and complete a lesson after being absent for 30+ days",
    rarity: "epic",
    isHidden: true,
  },
];